name: "NetCore Restore, Build and Publish"
description: "Template to NetCore"

inputs:
  WebAppPackagePath:
    description: “Folder to storage results of dotnet publish”
    required: true
  Configuration:
    description: “Configuration to Build application”
    required: true
  DotNetCoreVersion:
    description: “DotNet version”
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup .NET Core SDK ${{inputs.DotNetCoreVersion}}
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: ${{inputs.DotNetCoreVersion}}
  - name: Restore packages
    run: dotnet restore
    shell: bash
  - name: Build app
    run: dotnet build --configuration ${{inputs.Configuration}} --no-restore
    shell: bash
  - name: Test app
    run: dotnet test --no-build
    shell: bash
  - name: Publish app for deploy
    run: dotnet publish --configuration ${{inputs.Configuration}} --no-build --output "${{inputs.WebAppPackagePath}}"
    shell: bash
  - name: Upload a Build Artifact
    uses: actions/upload-artifact@v2.2.4
    with:
      name: NetCorePublish
      path: ${{inputs.WebAppPackagePath}}
    
